version: '3'

services:
  web_app:
    build: .
    command: node index.js
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - new
  db:
    image: postgres
    networks:
      new:
        aliases:
          - database
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=regina
      - POSTGRES_DB=users
networks:
  new: